
image: Visual Studio 2019

test_script:
  - ps: .\test.ps1 -image $env:APPVEYOR_BUILD_WORKER_IMAGE

build: off
#on_finish:
 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))